[package]
name = "IMPCF"
version = "0.1.0"
author = ["Lychnis"]
edition = "2021"

[dependencies]
lalrpop-util = { version = "0.21.0", features = ["lexer", "unicode"] }

[build-dependencies]
lalrpop = "0.21.0"
